config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashborad/', include('dashborad.urls')),
    path('enquete/', include('enquete.urls')),
    path('message/', include('message.urls')),
]

enquete/urls.py
from django.urls import path

from . import views

app_name = 'enquete'

urlpatterns = [
    path('list/', views.MemberList.as_view(), name='member_list'),
    path('create/', views.MemberCreate.as_view(), name='member_create'),
    path('detail/<member_id>/',
         views.MemberDetail.as_view(), name='member_detail'),
    path('update/<member_id>',
         views.MemberUpdate.as_view(), name='member_update'),
    path('delete/confirm/<member_id>',
         views.MemberDeleteConfirm.as_view(), name='member_delete_confrim'),
    path('delete/result/',
         views.MemberDeleteResult.as_view(), name='member_delete_result'),
    path('find/', views.MemberFind.as_view(), name='member_find'),
    path('sort/', views.MemberSort.as_view(), name='member_sort'),
    path('sort/<sort_key>', views.MemberSort.as_view(), name='member_sort_page'),
    path('page/<int:page_num>', views.MemberPage.as_view(), name='member_page'),
]

enquete/models.py
from django.db import models


# 部員マスタ
class MemberModel(models.Model):
    member_id = models.AutoField('部員ID', primary_key=True)
    member_name = models.CharField('部員名', max_length=100)
    registration_date = models.DateField('登録日', auto_now_add=True)
    delete_flag = models.BooleanField('削除フラグ', default=False)

    def __str__(self):
        return self.member_name


# アンケートマスタ
class EnqueteModel(models.Model):
    enquete_id = models.AutoField('アンケートID', primary_key=True)
    enquete_name = models.CharField('アンケート名', max_length=200)
    member_id = models.ForeignKey('MemberModel', on_delete=models.CASCADE)
    registration_date = models.DateField('登録日', auto_now_add=True)
    answer_date = models.DateField('回答日', null=True)
    delete_flag = models.BooleanField('削除フラグ', default=False)

    def __str__(self):
        return self.enquete_name

enquete/forms.py
from django import forms

import string


class MemberForms(forms.Form):
    """
    部員作成画面で使用するフォームクラス
    """
    member_name = forms.CharField(
        label='部員名',
        required=True,
        max_length=100
    )

    def clean_member_name(self):
        """
        カスタムバリデーションを行う関数
        clean_<フィールド名>で定義することで呼び出される
        """
        # 数字が使用されていないことを確認する
        member_name = self.cleaned_data['member_name']
        if 'admin' in member_name:
            raise forms.ValidationError('adminは名前に使用できません！')
        return member_name


class FindFroms(forms.Form):
    """
    検索ボックスとして使用するフォーム
    """
    find = forms.CharField(
        label='検索',
        required=False,
    )

enquete/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import View
from django.http import HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator

from . import models
from . import forms


class MemberList(View):
    """
    部員一覧画面を表示するクラス
    """

    def __init__(self):
        # 使用するmodelクラス
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        member_list = self.member_model.objects.all()
        context_data = {
            'member_list': member_list,
        }
        return render(request, 'member_list.html', context_data)


class MemberCreate(View):
    """
    部員作成画面を表示するクラス
    """

    def __init__(self):
        pass

    def get(self, request, *args, **kwargs):
        member_forms = forms.MemberForms(request.GET or None)
        context_data = {
            'forms': member_forms,
        }
        return render(request, 'member_create.html', context_data)

    def post(self, request, *args, **kwargs):
        member_forms = forms.MemberForms(request.POST or None)
        # 入力フォームにエラーがある場合
        if member_forms.errors:
            context_data = {
                'forms': member_forms,
            }
            return render(request, 'member_create.html', context_data)

        # 入力フォームがOKなら登録して一覧画面へリダイレクト
        member_name = request.POST['member_name']
        member = models.MemberModel(member_name=member_name)
        member.save()
        return redirect(to='/enquete/list/')


class MemberDetail(View):
    """
    部員の詳細画面を表示するクラス
    """

    def __init__(self):
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        member_forms = forms.MemberForms(request.GET or None)
        key_id = ''
        # クエリパラメータはrequest.GETに入るが
        # urlsで指定した変数はkwargsに入ってくる。
        if 'member_id' in kwargs:
            key_id = kwargs['member_id']

        member = self.member_model.objects.get(member_id=key_id)
        context_data = {
            'member': member,
            'forms': member_forms,
        }
        return render(request, 'member_detail.html', context_data)


class MemberUpdate(View):
    """
    部員の更新画面を表示するクラス
    """

    def __init__(self):
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        key_id = ''
        if 'member_id' in kwargs:
            key_id = kwargs['member_id']

        member = self.member_model.objects.get(member_id=key_id)

        # フォームの初期値を設定
        initial_dict = {
            'member_name': member.member_name,
        }

        member_forms = forms.MemberForms(request.GET or None,
                                         initial=initial_dict)
        context_data = {
            'member': member,
            'forms': member_forms
        }
        return render(request, 'member_update.html', context_data)

    def post(self, request, *args, **kwargs):
        member_forms = forms.MemberForms(request.POST or None)
        # 入力フォームにエラーがある場合
        if member_forms.errors:
            context_data = {
                'forms': member_forms,
            }
            return render(request, 'member_update.html', context_data)

        # クエリストURLからmember_idを取得　更新の検索キーにする
        key_id = ''
        if 'member_id' in kwargs:
            key_id = kwargs['member_id']

        # 入力フォームがOKなら更新して一覧画面へリダイレクト
        member = self.member_model.objects.get(member_id=key_id)
        member.member_name = request.POST['member_name']
        member.save()
        return redirect(to='/enquete/list/')


class MemberDeleteConfirm(View):
    """
    部員削除確認画面を表示するクラス
    """

    def __init__(self):
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        key_id = ''
        # url変数はkwargsに入っている
        if 'member_id' in kwargs:
            key_id = kwargs['member_id']

        member = self.member_model.objects.get(member_id=key_id)
        context_data = {
            'member': member,
        }
        return render(request, 'member_delete_confirm.html', context_data)

    def post(self, request, *args, **kwargs):
        key_id = ''
        if 'member_id' in kwargs:
            key_id = kwargs['member_id']

        member = self.member_model.objects.get(member_id=key_id)
        member.delete_flag = True
        member.save()
        return redirect(to='/enquete/delete/result')


class MemberDeleteResult(View):
    """
    部員削除確認画面を表示するクラス
    """

    def get(self, request, *args, **kwargs):
        return render(request, 'member_delete_result.html')


class MemberFind(View):
    """
    部員検索画面を表示するクラス
    """

    def __init__(self):
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        find_forms = forms.FindFroms(request.GET or None)
        context_data = {
            'forms': find_forms,
        }
        return render(request, 'member_find.html', context_data)

    def post(self, request, *args, **kwargs):
        find_forms = forms.FindFroms(request.POST or None)

        # 入力された検索キーで検索
        find_key = request.POST['find']
        # OR検索は以下のようにして行う
        # 検索結果のソートにはorder_byを使用する
        find_results = self.member_model.objects.filter(
            Q(member_name__contains=find_key) | Q(member_id__contains=find_key))\
            .order_by('member_name')

        context_data = {
            'find_results': find_results,
            'forms': find_forms,
        }
        return render(request, 'member_find.html', context_data)


class MemberSort(View):
    """
    ソート機能付きの部員一覧画面
    """

    def __init__(self):
        # 使用するmodelクラス
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        # 正規のソートキーが指定された場合に、ソートする
        # ソートキーが指定されてない場合は、defaultが入っているものとする
        sort_key = ''
        member_list = {}
        print(kwargs)
        if 'sort_key' in kwargs:
            sort_key = kwargs['sort_key']
            if sort_key != 'default':
                print(1)
                member_list = self.member_model.objects.all().order_by(sort_key)
            else:
                print(2)
                member_list = self.member_model.objects.all()

        context_data = {
            'member_list': member_list,
        }
        return render(request, 'member_sort.html', context_data)


class MemberPage(View):
    """
    ページング機能付きの一覧画面
    """

    def __init__(self):
        # 使用するmodelクラス
        self.member_model = models.MemberModel

    def get(self, request, *args, **kwargs):
        # ページングのUIは下記が参考になるかも
        # https://djangobrothers.com/blogs/django_pagination/
        member_list = self.member_model.objects.all()
        member_page = Paginator(member_list, 4)
        if 'page_num' in kwargs:
            page_num = kwargs.get('page_num', 1)
        print(request.GET)
        print(kwargs)
        context_data = {
            'member_list': member_page.get_page(page_num),
        }
        return render(request, 'member_page.html', context_data)

enquete/templates/member_create.html
<!DOCTYPE html>
<h1>部員作成画面</h1>

<form action="{% url 'enquete:member_create' %}" method="POST">
  <!-- csrf_token:postをする時には必ず入れる -->
  {% csrf_token %}
  <table border="1">
    {% for form in forms %}
    <tr>
      <th>{{ form.label}}</th>
      <td>{{ form }}</td>
      <!-- バリデーションエラー時に表示 -->
      {% if form.errors %}
      <td>{{ form.errors }}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </table>
  <button>作成</button>
</form>

enquete/templates/member_create_result.html
<!DOCTYPE html>

<h1>作成に成功しました！</h1>

enquete/templates/member_delete_confirm.html
<!DOCTYPE html>

<h1>部員削除画面(確認)</h1>

<h2>
  <p>※以下のデータを削除します。</p>
  <p>よろしければ、削除ボタンを押してください。</p>
</h2>

<form action="{% url 'enquete:member_delete_confrim' member.member_id %}" method="post">
  {% csrf_token %}

  <table border="1">
    <tr>
      <th>部員ID</th>
      <td>{{ member.member_id }}</td>
    </tr>
    <tr>
      <th>部員名</th>
      <td>{{ member.member_name }}</td>
    </tr>
    <tr>
      <th>登録日</th>
      <td>{{ member.registration_date }}</td>
    </tr>
    <tr>
      <th>ステータス</th>
      <td>
        {% if member.delete_flag %}
        無効
        {% else %}
        有効
        {% endif %}
      </td>
    </tr>
  </table>
  <button>削除</button>
</form>

enquete/templates/member_delete_result.html
<!DOCTYPE html>

<h1>部員削除画面(結果)</h1>

<h2>削除に成功しました。</h2>

<a href="{% url 'enquete:member_list' %}">
  一覧画面へ
</a>

enquete/templates/member_detail.html
<!DOCTYPE html>

<h1>部員詳細画面</h1>

<table border="1">
  <tr>
    <th>部員ID</th>
    <td>{{ member.member_id }}</td>
  </tr>
  <tr>
    <th>部員名</th>
    <td>{{ member.member_name }}</td>
  </tr>
  <tr>
    <th>登録日</th>
    <td>{{ member.registration_date }}</td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td>
      {% if member.delete_flag %}
      無効
      {% else %}
      有効
      {% endif %}
    </td>
  </tr>
</table>

enquete/templates/member_find.html
<!DOCTYPE html>

<h1>検索画面</h1>

<!-- 検索ボックス -->
<form action="{% url 'enquete:member_find' %}" method="post">
  <!-- csrf_token:postをする時には必ず入れる -->
  {% csrf_token %}
  <table border="1">
    <tr>
      <th>{{ forms.find.label }}</th>
      <td>{{ forms.find }}</td>
    </tr>
  </table>
  <button>検索</button>
</form>

<!-- 検索結果の一覧を表示 -->
<table border="1">
  <tr>
    <th>部員ID</th>
    <th>部員名</th>
    <th>登録日</th>
    <th>ステータス</th>
  </tr>
  {% for result in find_results %}
  <tr>
    <td>{{ result.member_id }}</td>
    <td>{{ result.member_name }}</td>
    <td>{{ result.registration_date }}</td>
    <td>
      {% if result.delete_flag %}
      無効
      {% else %}
      有効
      {% endif %}</td>
  </tr>
  {% endfor %}
</table>

enquete/templates/member_list.html
<h1>部員一覧画面</h1>

<table border="1">
  <tr>
    <th>部員ID</th>
    <th>
      <a href="{% url 'enquete:member_sort_page' 'member_name' %}">
        部員名</a>
    </th>
    <th>登録日</th>
    <th>ステータス</th>
    <th>更新</th>
    <th>削除</th>
  </tr>
  {% for member in member_list %}
  <tr>
    <td>
      <a href="{% url 'enquete:member_detail' member.member_id %}">{{ member.member_id }}</a>
    </td>
    <td>{{ member.member_name }}</td>
    <td>{{ member.registration_date }}</td>
    <td>
      {% if member.delete_flag %}
      無効
      {% else %}
      有効
      {% endif %}
    </td>
    <td>
      <a href="{% url 'enquete:member_update' member.member_id %}">更新する</a>
    </td>
    <td>
      <a href="{% url 'enquete:member_delete_confrim' member.member_id %}">削除する</a>
    </td>
  </tr>
  {% endfor %}
</table>

enquete/templates/member_page.html
<h1>部員一覧画面(ページング付き)</h1>

<table border="1">
  <tr>
    <th>部員ID</th>
    <th>部員名</th>
    <th>登録日</th>
    <th>ステータス</th>
    <th>更新</th>
    <th>削除</th>
  </tr>
  {% for member in member_list %}
  <tr>
    <td>
      <a href="{% url 'enquete:member_detail' member.member_id %}">{{ member.member_id }}</a>
    </td>
    <td>{{ member.member_name }}</td>
    <td>{{ member.registration_date }}</td>
    <td>
      {% if member.delete_flag %}
      無効
      {% else %}
      有効
      {% endif %}
    </td>
    <td>
      <a href="{% url 'enquete:member_update' member.member_id %}">更新する</a>
    </td>
    <td>
      <a href="{% url 'enquete:member_delete_confrim' member.member_id %}">削除する</a>
    </td>
  </tr>
  {% endfor %}
</table>
<!-- ページネーション -->
<div >
  {% if member_list.has_previous %}
  <a href="{% url 'enquete:member_page' 1 %}">prev</a>
  {% endif %}
</div>

enquete/templates/member_sort.html
<h1>部員一覧画面(ソート機能つき)</h1>

<table border="1">
  <tr>
    <th>部員ID</th>
    <th>
        <a href="{% url 'enquete:member_sort' 'member_name' %}">
          項目名
        </a>
    </th>
    <th>登録日</th>
    <th>ステータス</th>
    <th>更新</th>
    <th>削除</th>
  </tr>
  {% for member in member_list %}
  <tr>
    <td>
      <a href="{% url 'enquete:member_detail' member.member_id %}">{{ member.member_id }}</a>
    </td>
    <td>{{ member.member_name }}</td>
    <td>{{ member.registration_date }}</td>
    <td>
      {% if member.delete_flag %}
      無効
      {% else %}
      有効
      {% endif %}
    </td>
    <td>
      <a href="{% url 'enquete:member_update' member.member_id %}">更新する</a>
    </td>
    <td>
      <a href="{% url 'enquete:member_delete_confrim' member.member_id %}">削除する</a>
    </td>
  </tr>
  {% endfor %}
</table>

enquete/templates/member_update.html
<!DOCTYPE html>

<h1>部員更新画面</h1>
<form action="{% url 'enquete:member_update' member.member_id %}" method="post">
  {% csrf_token %}
  <table border="1">
    <tr>
      <th>部員ID</th>
      <td>
        {{ member.member_id }}
      </td>
    </tr>
    <tr>
      <th>部員名</th>
      <td>
        {{ forms.member_name }}
      </td>
      {% if forms.errors %}
      <td>
        {{ forms.errors }}
      </td>
      {% endif %}
    </tr>
    <tr>
      <th>登録日</th>
      <td>
        {{ member.registration_date }}
      </td>
    </tr>
    <tr>
      <th>ステータス</th>
      <td>
        {% if member.delete_flag %}
        無効
        {% else %}
        有効
        {% endif %}
      </td>
    </tr>
  </table>
  <button>更新</button>
</form>