config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashborad/', include('dashborad.urls')),
    path('enquete/', include('enquete.urls')),
    path('message/', include('message.urls')),
]

message/urls.py
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    path('list/', views.MessageList.as_view(), name='message_list'),
    path('list/<int:page>', views.MessageList.as_view(),
         name='message_list_page'),
    path('form_test/', views.FormTest.as_view(), name='form_test'),
]

message/models.py
from django.db import models


# 人物マスタ
class FriendModel(models.Model):
    name = models.CharField(max_length=100)
    mail = models.CharField(max_length=200)
    gender = models.BooleanField()
    age = models.IntegerField(default=0)
    birthday = models.DateField()

    def __str__(self):
        return self.name


class MessageModel(models.Model):
    friend = models.ForeignKey(FriendModel, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + ' posted by ' + self.friend.name

    class Meta:
        # デフォルトでのソート順を指定する
        ordering = ('pub_date',)

message/forms.py
from django import forms

from .models import MessageModel


class MessageForm(forms.ModelForm):
    class Meta:
        model = MessageModel
        fields = ['title', 'content', 'friend']


class TestForm(forms.Form):
    """
    いろんな種類のフォームを試すためのフォームクラス
    """
    text = forms.CharField(
        label='name',
        required=False,
        max_length=10,
        min_length=5)
    mail = forms.EmailField(
        label='email',
        required=False,
        max_length=10,
        min_length=5
    )
    number_int = forms.IntegerField(
        required=False,
        label='int数字',
        help_text='数字を入力してください',
        max_value=100,
        min_value=5
    )
    float_num = forms.FloatField(
        required=False,
        max_value=10,
    )
    url_text = forms.URLField(
        required=False,
        label='URL入力',
        max_length=10,
        min_length=5,
    )
    # DateFieldのtype="date"にする方法
    # 参考) https://qiita.com/felyce/items/726496b9cecdaf05b6b1
    date_text = forms.DateField(
        required=False,
        label='日付',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    # TimeFieldのtype="time"にするのも上記と同じ方法でできる
    time_text = forms.TimeField(
        required=False,
        label='時間',
        widget=forms.TimeInput(attrs={'type': 'time'})
    )
    check_box_1 = forms.BooleanField(
        label='check 1',
        required=False,
    )
    check_box_2 = forms.BooleanField(
        label='check 2',
        required=False,
    )
    null_bool = forms.NullBooleanField(
        label='3択',
        required=False,
    )

message/views.py
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator

from . import models
from . import forms


class MessageList(View):
    """
    投稿一覧画面を表示するクラス
    """

    def __init__(self):
        self.message_model = models.MessageModel
        self.friend_model = models.FriendModel

    def get(self, request, *args, **kwargs):
        # ページング
        page = kwargs.get('page', 1)

        message_list = self.message_model.objects.all()
        message_page = Paginator(message_list, 3)

        friend_list = self.friend_model.objects.all()
        for friend in friend_list:
            print(friend)

        context_data = {
            'message_forms': forms.MessageForm(),
            'message_list': message_page.get_page(page),
            'friend_list': friend_list,
        }
        return render(request, 'message_list.html', context_data)

    def post(self, request, *args, **kwargs):
        # 投稿の作成
        obj = models.MessageModel()
        message_form = forms.MessageForm(request.POST, instance=obj)
        message_form.save()

        message_list = self.message_model.objects.all()
        message_page = Paginator(message_list, 3)

        friend_list = self.friend_model.objects.all()

        context_data = {
            'message_forms': forms.MessageForm(),
            'message_list': message_page.get_page(1),
            'friend_list': friend_list,

        }
        return render(request, 'message_list.html', context_data)


class FormTest(View):
    """
    いろんな種類のformの動作確認用のクラス
    """

    def get(self, request, *args, **kwargs):
        context_data = {
            'goto': 'message:form_test',
            'forms': forms.TestForm(),
        }
        return render(request, 'form_test.html', context_data)

    def post(self, request, *args, **kwargs):
        text_data = request.POST.get('text_input', None)
        print(request.POST)
        context_data = {
            'goto': 'message:form_test',
            'text_data': text_data,
            'forms': forms.TestForm(request.POST),
        }
        return render(request, 'form_test.html', context_data)

message/templates/base_test.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- cssを配置する領域 -->
  {% block css %}
  {% endblock %}

  <!-- titleタグを記述する領域 -->
  {% block title %}
  {% endblock%}

</head>

<body>
  <div class="container">
    <!-- コンテンツを記述する領域 -->
    {% block main%}
    {% endblock%}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

  <!-- スクリプトを記述する領域 -->
  {% block script %}
  {% endblock %}
</body>

</html>

message/templates/boot_test.html
{% extends "base_test.html" %}

{% block css %}
<style>
  .hide {
    display: none;
  }
</style>
{% endblock%}


{% block title %}
<title>アンケートフォーム作成(テスト)</title>
{% endblock %}

{% block main %}
<h1>アンケートフォーム作成(テスト)</h1>

<form action="{% url 'message:boot_test' %}" method="post" id="id_master_form">
  {% csrf_token %}
  <label>アンケートタイトル</label>
  {{ forms.Q_name }}
  <div id="1">
    <p>
      <label>質問文</label>
      {{ forms.Q_text }}
    </p>
    <p>
      <label>回答方法</label>
      {{ forms.Q_type }}
    </p>

    <div class="choice">
      <p id="id_choice" class="hide">
        <label>選択肢</label>
        {{ forms.Q_choice }}
        <input type="button" value="＋" class="add">
        <input type="button" value="－" class="del">
      </p>
    </div>
  </div>

  <!-- 質問を追加する領域 -->
  <div id="id_addtional_Q"></div>

  <input type="submit" value="送信する">
</form>

<div>
  <button id="id_add_button">質問を追加</button>
</div>
{% endblock %}


{% block script %}
<script>
  //　最新の質問番号
  let Q_num = 1

  // onを使うと簡単に複数イベントを設定することができる
  $('#id_add_button').on('click', function(){
    Q_num = Q_num + 1

    // 新しいnameの生成
    let name_Q_choice = 'Q_choice' + '_' + Q_num

    // 大元の質問を複製
    let question = $('#1').clone(true)

    question.find('#id_Q_choice').attr('name', name_Q_choice)

    // 新しい質問の追加
    question.appendTo('#id_addtional_Q')

  })

  // 選択肢の入力項目を表示させる  
  $('.Q_type').change(function () {
    if ($(this).val() !== 'text') {
      $(this).parent().parent().find('#id_choice').removeClass("hide")
    }
    else {
      $(this).parent().parent().find('#id_choice').addClass("hide")
    }
  })
  
  // 選択肢の追加
  $('.add').on("click", function () {
    $(this).parent().clone(true).insertAfter($(this).parent());
  });
  $('.del').on("click", function () {
    var target = $(this).parent();
    if (target.parent().children().length > 1) {
      target.remove();
    }
  });

</script>
{% endblock %}

message/templates/form_test.html
<h1>いろんな種類のフォーム</h1>

<form action="{% url goto %}" method="post">
  {% csrf_token %}
  <label for="id_text_input">テキスト：</label>
  <input type="text" name="text_input" id="id_text_input">
  <button>送信</button>
</form>

<h4>送信結果</h4>
{% if text_data %}
<p>テキスト：{{ text_data }}</p>
{% endif %}

<h4>フォームクラスを使用したフォーム</h4>

<form action="{% url goto %}" method="post">
  {% csrf_token %}
  {{ forms.as_p }}
  <button>送信する</button>
</form>

message/templates/message_list.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>

<body>
  <h1>投稿一覧画面</h1>

  <form action="{% url 'message:message_list' %}" method="post">
    {% csrf_token %}
    <table border="1">
      <tr>
        <th>投稿者</th>
        <td>{{ message_forms.friend }}</td>
      </tr>
      <tr>
        <th>タイトル</th>
        <td>{{ message_forms.title }}</td>
      </tr>
      <tr>
        <th>内容</th>
        <td>{{ message_forms.content }}</td>
      </tr>
    </table>
    <button>投稿</button>
  </form>

  <table border="1">
    <tr>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>投稿日</th>
    </tr>
    {% for message in message_list %}
    <tr>
      <td>{{ message.title }}</td>
      <td>{{ message.friend.name }}</td>
      <td>{{ message.title }}</td>
    </tr>
    {% endfor %}
  </table>

  <nav aria-label="Page navigation">
    <ul class="pagination">
      <!-- 前のページに戻る -->
      {% if message_list.has_previous %}
      <li class="page-item"><a class="page-link"
          href="{% url 'message:message_list_page' message_list.previous_page_number %}">prev</a>
      </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="#">prev</a>
      </li>
      {% endif %}

      <!-- ページ番号 -->
      {% if message_list.number != 1 %}
      <li class="page-item"><a class="page-link" href="{% url 'message:message_list_page' 1 %}">1</a></li>
      <li class="page-item"><span>&hellip;</span></li>
      {% endif %}

      <li class="page-item"><a class="page-link"
          href="{% url 'message:message_list_page' message_list.number %}">{{ message_list.number }}</a>
      </li>

      {% if message_list.has_next and message_list.next_page_number != message_list.paginator.num_pages %}
      <li class="page-item"><a class="page-link"
          href="{% url 'message:message_list_page' message_list.next_page_number %}">{{ message_list.next_page_number }}</a>
      </li>
      {% endif %}

      {% if message_list.number != message_list.paginator.num_pages %}
      <li class="page-item"><span>&hellip;</span></li>
      <li class="page-item"><a class="page-link"
          href="{% url 'message:message_list_page' message_list.paginator.num_pages %}">{{ message_list.paginator.num_pages }}</a>
      </li>
      {% endif %}

      <!-- 次のページに進む -->
      {% if message_list.has_next %}
      <li class="page-item"><a class="page-link"
          href="{% url 'message:message_list_page' message_list.next_page_number %}">next</a>
      </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="#">next</a>
      </li>
      {% endif %}

    </ul>
  </nav>

  <!-- Friendテーブル -->
  <table border="1">
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>メール</th>
      <th>誕生日</th>
      <th>投稿タイトル</th>
    </tr>
    {% for friend in friend_list %}
    <tr>
      <td>{{ friend.id }}</td>
      <td>{{ friend.name }}</td>
      <td>{{ friend.mail }}</td>
      <td>{{ friend.birthday }}</td>
      <td>
        <ul>
          {% for ob in friend.messagemodel_set.all %}
          <li>{{ ob.title }}</li>
          {% endfor %}
        </ul>
      </td>
    </tr>
    {% endfor %}
  </table>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>